/* src/env/static/public.ts */

export const PUBLIC_BASE_URL = import.meta.env.PUBLIC_BASE_URL;
export const PUBLIC_API_URL = import.meta.env.PUBLIC_API_URL;
export const PUBLIC_CSV_FILE_UPLOAD_LIMIT = import.meta.env
  .PUBLIC_CSV_FILE_UPLOAD_LIMIT;
export const PUBLIC_VIDEO_BASE_URL = import.meta.env.PUBLIC_VIDEO_BASE_URL;
export const PUBLIC_OPENREPLAY_PROJECT_KEY = import.meta.env
  .PUBLIC_OPENREPLAY_PROJECT_KEY;
export const PUBLIC_OPENREPLAY_INGEST_POINT = import.meta.env
  .PUBLIC_OPENREPLAY_INGEST_POINT;
export const PUBLIC_ELASTIC_APM_SERVICE_NAME = import.meta.env
  .PUBLIC_ELASTIC_APM_SERVICE_NAME;
export const PUBLIC_ELASTIC_APM_SERVER_URL = import.meta.env
  .PUBLIC_ELASTIC_APM_SERVER_URL;
export const PUBLIC_ELASTIC_APM_SERVICE_VERSION = import.meta.env
  .PUBLIC_ELASTIC_APM_SERVICE_VERSION;
export const PUBLIC_ELASTIC_APM_ENVIRONMENT = import.meta.env
  .PUBLIC_ELASTIC_APM_ENVIRONMENT;
export const PUBLIC_ELASTIC_APM_DISTRIBUTED_TRACING_ORIGINS = import.meta.env
  .PUBLIC_ELASTIC_APM_DISTRIBUTED_TRACING_ORIGINS;
