/* src/frontend-config.ts */

import {
  PUBLIC_OPENREPLAY_PROJECT_KEY,
  PUBLIC_OPENREPLAY_INGEST_POINT,
  PUBLIC_CSV_FILE_UPLOAD_LIMIT,
  PUBLIC_ELASTIC_APM_SERVICE_NAME,
  PUBLIC_ELASTIC_APM_SERVER_URL,
  PUBLIC_ELASTIC_APM_SERVICE_VERSION,
  PUBLIC_ELASTIC_APM_ENVIRONMENT,
} from "$env/static/public";

// Debug log
// console.log("Environment Variables:", {
//   PUBLIC_OPENREPLAY_PROJECT_KEY,
//   PUBLIC_OPENREPLAY_INGEST_POINT,
//   PUBLIC_CSV_FILE_UPLOAD_LIMIT,
//   PUBLIC_ELASTIC_APM_SERVICE_NAME,
//   PUBLIC_ELASTIC_APM_SERVER_URL,
//   PUBLIC_ELASTIC_APM_SERVICE_VERSION,
//   PUBLIC_ELASTIC_APM_ENVIRONMENT,
// });

import type { FrontendConfig } from "./models/types";

export const frontendConfig: FrontendConfig = {
  openreplay: {
    PROJECT_KEY: PUBLIC_OPENREPLAY_PROJECT_KEY,
    INGEST_POINT: PUBLIC_OPENREPLAY_INGEST_POINT,
  },
  csv: {
    FILE_UPLOAD_LIMIT: Number(PUBLIC_CSV_FILE_UPLOAD_LIMIT),
  },
  elasticApm: {
    SERVICE_NAME: PUBLIC_ELASTIC_APM_SERVICE_NAME,
    SERVER_URL: PUBLIC_ELASTIC_APM_SERVER_URL,
    SERVICE_VERSION: PUBLIC_ELASTIC_APM_SERVICE_VERSION,
    ENVIRONMENT: PUBLIC_ELASTIC_APM_ENVIRONMENT,
  },
} as const;

export type { FrontendConfig } from "./models/types";
